src/main/java/me/saiintbrisson/inventory/ItemBuilder.java

When you was trying to create the lore with this method it was throwing a NullPointerException.

Fixed NullPointerException

---

THIRDPARTY.md
build.gradle
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
settings.gradle
src/main/java/com/cryptomorin/xseries/ReflectionUtils.java
src/main/java/me/matsubara/roulette/util/InventoryUpdate.java
src/main/java/me/saiintbrisson/minecraft/ViewContext.java
src/main/resources/plugin.yml

1.17 and 1.18 dynamic title update compatibility

---

CHANGELOG.md
src/main/java/me/saiintbrisson/minecraft/PaginatedView.java

Previous and next page items aren't displayed if item slot is manually defined

---

bukkit-api/src/main/java/me/saiintbrisson/minecraft/BukkitClickViewSlotContext.java
bukkit-api/src/main/java/me/saiintbrisson/minecraft/BukkitEntityViewContainer.java
bukkit-api/src/main/java/me/saiintbrisson/minecraft/GlobalClickInterceptor.java
bukkit-api/src/main/java/me/saiintbrisson/minecraft/ViewListener.java
bukkit-plugin/src/main/java/me/saiintbrisson/minecraft/InventoryFramework.java
feature-move-io/src/main/java/me/saiintbrisson/minecraft/ViewSlotMoveContextImpl.java
shared/src/main/java/me/saiintbrisson/minecraft/AbstractViewSlotContext.java
shared/src/main/java/me/saiintbrisson/minecraft/ViewType.java

Fixes `isOnEntityContainer` checks

Instantiate entity container properly

---

shared/src/main/java/me/saiintbrisson/minecraft/AbstractViewSlotContext.java
shared/src/main/java/me/saiintbrisson/minecraft/BaseViewContext.java
shared/src/main/java/me/saiintbrisson/minecraft/ViewContext.java
shared/src/test/java/me/saiintbrisson/minecraft/ContextDataInheritanceTest.java

Slot context data inheritance

---

shared/src/main/java/me/saiintbrisson/minecraft/AbstractView.java
shared/src/main/java/me/saiintbrisson/minecraft/BasePaginatedViewContext.java

NPE in context's paginator

---

shared/src/main/java/me/saiintbrisson/minecraft/AbstractView.java

Try to fix ConcurrentModificationException on open

---

shared/src/main/java/me/saiintbrisson/minecraft/pipeline/interceptors/LayoutPatternApplierInterceptor.java

ViewItem is mutable so a new instance must be created per slot

Fix user-defined layout pattern iteration index and item

---

platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java

Set default type for view config to CHEST

---

api/src/main/java/me/devnatan/inventoryframework/ViewType.java
bukkit/src/main/java/me/devnatan/inventoryframework/internal/BukkitElementFactory.java
bukkit/src/main/java/me/devnatan/inventoryframework/runtime/BukkitViewContainer.java
bukkit/src/main/java/me/devnatan/inventoryframework/runtime/BukkitViewer.java
bukkit/src/main/java/me/devnatan/inventoryframework/runtime/util/InventoryUtils.java
platform/src/main/java/me/devnatan/inventoryframework/context/PlatformRenderContext.java

Support more inventory types

---

api/src/main/java/me/devnatan/inventoryframework/component/Component.java
api/src/main/java/me/devnatan/inventoryframework/component/ItemComponent.java
api/src/main/java/me/devnatan/inventoryframework/component/PaginationElementFactory.java
api/src/main/java/me/devnatan/inventoryframework/internal/ElementFactory.java
bukkit/src/main/java/me/devnatan/inventoryframework/component/BukkitItemComponentBuilder.java
bukkit/src/main/java/me/devnatan/inventoryframework/context/RenderContext.java
bukkit/src/main/java/me/devnatan/inventoryframework/internal/BukkitElementFactory.java
bukkit/src/main/java/me/devnatan/inventoryframework/runtime/listener/IFInventoryListener.java
framework/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
framework/src/main/java/me/devnatan/inventoryframework/pipeline/UpdateInterceptor.java
platform/src/main/java/me/devnatan/inventoryframework/PaginationStateBuilder.java
platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java
test/src/main/java/me/devnatan/inventoryframework/component/FakeComponent.java
test/src/main/java/me/devnatan/inventoryframework/internal/MockElementFactory.java

Simplified conditional rendering

---

bukkit/src/main/java/me/devnatan/inventoryframework/runtime/listener/IFInventoryListener.java
framework/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
framework/src/test/java/me/devnatan/inventoryframework/component/PaginationImplTest.java

Handle pagination click interaction

---

.github/workflows/publish.yml
bom/build.gradle
build.gradle
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
jitpack.yml
publish.gradle

Publish on Maven Central

---

bukkit/src/main/java/me/devnatan/inventoryframework/runtime/util/InventoryUtils.java

Register pre-1.8 inventory types manually

---

bukkit/src/main/java/me/devnatan/inventoryframework/pipeline/GlobalClickInterceptor.java

Mark global click context as cancelled

---

framework/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
platform/src/main/java/me/devnatan/inventoryframework/pipeline/PlatformOpenInterceptor.java
platform/src/main/java/me/devnatan/inventoryframework/pipeline/PlatformRenderInterceptor.java

Render initialization order and pagination issues

---

bukkit/src/main/java/me/devnatan/inventoryframework/component/BukkitItemComponentBuilder.java

Allows
```java
render.layoutSlot('<', new ItemStack(Material.ARROW))
.displayIf(pagination::canBack)
.onClick(pagination::back);
```

Click handler overload

---

CHANGELOG.md
README.md
THIRDPARTY.md
api/src/main/java/me/devnatan/inventoryframework/context/IFRenderContext.java
api/src/main/java/me/devnatan/inventoryframework/state/MutableState.java
build.gradle
bukkit/src/main/java/me/devnatan/inventoryframework/component/BukkitItemComponentBuilder.java
bukkit/src/main/java/me/devnatan/inventoryframework/context/SlotClickContext.java
bukkit/src/main/java/me/devnatan/inventoryframework/runtime/InventoryFramework.java
framework/src/main/java/me/devnatan/inventoryframework/state/PaginationState.java
paper/src/main/java/me/devnatan/inventoryframework/internal/PaperInventoryFactory.java
platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java
platform/src/main/java/me/devnatan/inventoryframework/context/PlatformRenderContext.java

Version 3.0.0-alpha

---

api/src/main/java/me/devnatan/inventoryframework/IFViewFrame.java
api/src/main/java/me/devnatan/inventoryframework/RootView.java
api/src/main/java/me/devnatan/inventoryframework/event/EventBus.java
api/src/main/java/me/devnatan/inventoryframework/feature/Feature.java
api/src/main/java/me/devnatan/inventoryframework/state/MutableState.java
bukkit/build.gradle
bukkit/src/main/java/me/devnatan/inventoryframework/runtime/InventoryFramework.java
feature-eventbus/build.gradle
feature-eventbus/src/main/java/me/devnatan/inventoryframework/feature/eventbus/EventBusFeature.java
framework/src/main/java/me/devnatan/inventoryframework/DefaultRootView.java
platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java
settings.gradle

https://github.com/DevNatan/inventory-framework/wiki/Event-Bus

Event bus feature

---

bukkit/src/main/java/me/devnatan/inventoryframework/ViewFrame.java

Check for InventoryFramework class in runtime to warn about relocation issues

---

api/src/main/java/me/devnatan/inventoryframework/context/IFConfinedContext.java
api/src/main/java/me/devnatan/inventoryframework/context/IFContext.java
bukkit/src/main/java/me/devnatan/inventoryframework/context/OpenContext.java
framework/src/main/java/me/devnatan/inventoryframework/context/BaseViewContext.java
platform/src/main/java/me/devnatan/inventoryframework/context/ConfinedContext.java

openForPlayer and openForEveryone with initial data

---

bukkit/src/main/java/me/devnatan/inventoryframework/runtime/thirdparty/InventoryUpdate.java
bukkit/src/main/java/me/devnatan/inventoryframework/runtime/thirdparty/ReflectionUtils.java
gradle/libs.versions.toml

Minecraft 1.19 and 1.20 support

---

CHANGELOG.md
api/src/main/java/me/devnatan/inventoryframework/component/ItemComponent.java
api/src/main/java/me/devnatan/inventoryframework/context/IFContext.java
api/src/main/java/me/devnatan/inventoryframework/context/IFSlotContext.java
bukkit/src/main/java/me/devnatan/inventoryframework/component/BukkitItemComponentBuilder.java
bukkit/src/main/java/me/devnatan/inventoryframework/context/SlotContext.java
framework/src/main/java/me/devnatan/inventoryframework/DefaultRootView.java
framework/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
framework/src/main/java/me/devnatan/inventoryframework/context/BaseViewContext.java
framework/src/main/java/me/devnatan/inventoryframework/pipeline/FirstRenderInterceptor.java
framework/src/main/java/me/devnatan/inventoryframework/pipeline/UpdateInterceptor.java
framework/src/test/java/me/devnatan/inventoryframework/pipeline/UpdateInterceptorTest.java
test/src/main/java/me/devnatan/inventoryframework/TestUtils.java
test/src/main/java/me/devnatan/inventoryframework/internal/MockElementFactory.java

Makes each component, in its own implementation, determine how it will handle updates.
Using an item with render handler `itemFactory((item, value) -> item.onRender(...))` in Pagination state plus `context.update()` should work now

Handle update individually by component

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/Pagination.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/state/StateValue.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/runtime/InventoryFramework.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java

Allows usage of CompletableFuture as pagination data source. Introduces new `asyncPaginationState` and `buildAsyncPaginationState` marked as experimental methods. Documentation is "Asynchronous Data Source" on Wiki.

Asynchronous pagination data source

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/ViewConfig.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/ViewConfigBuilder.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/Viewer.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/pipeline/ViewerLastInteractionTrackerInterceptor.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/pipeline/ViewerLastInteractionUpdaterInterceptor.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/BukkitViewer.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/context/SlotClickContext.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/pipeline/GlobalClickInterceptor.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/pipeline/ItemClickInterceptor.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java

Implements #454
Can be applied in ViewFrame defaultConfig that applies to all registered views)
```java
viewFrame.defaultConfig(config -> config.interactionDelay(duration))
```
or View configuration
```java
@Override
public void onInit(ViewConfigBuilder config) {
config.interactionDelay(duration)
}
```

Interaction delay config

---

inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/IFInventoryListener.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/pipeline/ItemClickInterceptor.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/pipeline/ItemCloseOnClickInterceptor.java

Fixes https://www.youtube.com/watch?v=oLQq5QXuNPk

Never skip click handling

---

inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java

Close viewer inventory before transition

---

inventory-framework-anvil-input/src/main/java/me/devnatan/inventoryframework/AnvilInput.java
inventory-framework-anvil-input/src/main/java/me/devnatan/inventoryframework/AnvilInputConfig.java
inventory-framework-anvil-input/src/main/java/me/devnatan/inventoryframework/AnvilInputFeature.java
inventory-framework-anvil-input/src/main/java/me/devnatan/inventoryframework/AnvilInputStateValue.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/ViewType.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/ItemComponent.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/ViewFrame.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/context/SlotContext.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/feature/DefaultFeatureInstaller.java

Continuation of #477
Configuration can be done via
```java
viewFrame.install(AnvilInput, config -> config.initialTitle("...").closeOnSelect());
```

Anvil input integration enhancements

---

inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/context/PlatformRenderContext.java

Remove multiple layoutSlot with same character restriction

---

inventory-framework-core/src/main/java/me/devnatan/inventoryframework/pipeline/ScheduledUpdateAfterCloseInterceptor.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/context/CloseContext.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/pipeline/ContextInvalidationOnCloseInterceptor.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/pipeline/PlatformCloseInterceptor.java

Close interceptor fixes and cancellation issues

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/ComponentBuilder.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/component/DefaultComponentBuilder.java

Modify #updateOnStateChange to prohibit no-parameter usage

---

inventory-framework-core/src/main/java/me/devnatan/inventoryframework/state/PaginationState.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/state/StateAccessImpl.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java

Fix pagination state can only be registered by RootView

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/context/IFRenderContext.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/pipeline/AvailableSlotInterceptor.java
inventory-framework-core/src/test/java/me/devnatan/inventoryframework/pipeline/AvailableSlotInterceptorTest.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/context/RenderContext.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/context/PlatformRenderContext.java
inventory-framework-platform/src/test/java/me/devnatan/inventoryframework/context/PlatformRenderContextTest.java

| Before | After |
|--------|--------|
| ![Screenshot 2023-11-24 at 19 23 46](https://github.com/DevNatan/inventory-framework/assets/24600258/2b34a822-84a3-483a-99a8-8696ab0d7a4b) | ![Screenshot 2023-11-24 at 19 32 30](https://github.com/DevNatan/inventory-framework/assets/24600258/e2f8f849-bc06-4b25-9bd4-6164263d2225) |

Do not fill everything when `availableSlot()` is used

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/context/IFContext.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/context/IFSlotClickContext.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/context/AbstractIFContext.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/IFInventoryListener.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/context/SlotClickContext.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/context/SlotContext.java

Repropagates click interaction for pagination child, now all click interceptors are properly called in pagination child

Repropagate click interaction in pagination child

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/context/IFContext.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/context/IFSlotClickContext.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/internal/ElementFactory.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/context/AbstractIFContext.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/pipeline/ComponentClickHandlerCallInterceptor.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/pipeline/ViewerLastInteractionTrackerInterceptor.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/IFInventoryListener.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/context/SlotClickContext.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/context/SlotContext.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/internal/BukkitElementFactory.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/context/PlatformContext.java

Repropagated interactions like Pagination -> Child was being intercepted by `interactionDelay` config thus not working

Interaction delay intercepting repropagated interactions

---

inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/internal/InventoryFactory.java
inventory-framework-platform-paper/build.gradle
inventory-framework-platform-paper/src/main/java/me/devnatan/inventoryframework/internal/PaperInventoryFactory.java

Kyori's Adventure components should work now
https://github.com/DevNatan/inventory-framework/wiki/configuration-guide#titlenetkyoriadventuretextcomponent

Fix using Paper as inventory factory

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/context/IFSlotClickContext.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/internal/LayoutSlot.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/context/SlotClickContext.java

Create `isLayoutSlot([...])` in SlotClickContext

---

inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/context/ContextOpenInterceptor.java

Check if state is mutable before redefine value on open

---

inventory-framework-anvil-input/src/main/java/me/devnatan/inventoryframework/AnvilInputFeature.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/context/IFContext.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/pipeline/PipelinePhase.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/DefaultRootView.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/context/AbstractIFContext.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/context/OpenContext.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/context/SlotContext.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/ViewContextOpenInterceptor.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/context/ContextPlatformRenderHandlerCallInterceptor.java

Move CONTEXT_OPEN pipeline phase to view scope and create "before render" phase

---

inventory-framework-anvil-input/src/main/java/me/devnatan/inventoryframework/AnvilInputFeature.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/ViewConfigBuilder.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/pipeline/PipelinePhase.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/component/AbstractComponent.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/component/AbstractComponentBuilder.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/component/AbstractBukkitComponent.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/component/AbstractBukkitComponentBuilder.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/component/BukkitComponent.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/component/BukkitComponentBuilder.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/context/ComponentRenderContext.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/component/PlatformComponentBuilder.java

Fixes #642
Fixes #643
Fixes #644

Fix platform component rendering and pipeline order

---

inventory-framework-core/src/test/java/me/devnatan/inventoryframework/component/PaginationImplTest.java
inventory-framework-core/src/test/java/me/devnatan/inventoryframework/pipeline/AvailableSlotInterceptorTest.java
inventory-framework-core/src/test/java/me/devnatan/inventoryframework/pipeline/FirstRenderInterceptorTest.java
inventory-framework-core/src/test/java/me/devnatan/inventoryframework/pipeline/UpdateInterceptorTest.java
inventory-framework-platform-bukkit/src/test/java/me/devnatan/inventoryframework/BukkitTestUtils.java
inventory-framework-platform-bukkit/src/test/java/me/devnatan/inventoryframework/IFInventoryListenerTest.java
inventory-framework-platform/src/test/java/me/devnatan/inventoryframework/component/TestItemComponentBuilder.java
inventory-framework-platform/src/test/java/me/devnatan/inventoryframework/context/PlatformRenderContextTest.java
inventory-framework-test/src/main/java/me/devnatan/inventoryframework/TestUtils.java
inventory-framework-test/src/main/java/me/devnatan/inventoryframework/context/MockRenderIFContext.java
inventory-framework-test/src/main/java/me/devnatan/inventoryframework/internal/MockElementFactory.java

Well fixes most of the existing unit-test or disabled if I did not know how to fix them.

Fix most of the unit-test that I could fix

---

.github/workflows/build.yml
.github/workflows/generate-artifacts.yml
.github/workflows/publish.yml
.github/workflows/test.yml
example/build.gradle
example/src/main/java/me/devnatan/inventoryframework/runtime/ExampleUtil.java
example/src/main/java/me/devnatan/inventoryframework/runtime/SamplePlugin.java
example/src/main/java/me/devnatan/inventoryframework/runtime/commands/IFExampleCommandExecutor.java
example/src/main/java/me/devnatan/inventoryframework/runtime/view/AnvilInputSample.java
example/src/main/java/me/devnatan/inventoryframework/runtime/view/Failing.java
example/src/main/java/me/devnatan/inventoryframework/runtime/view/SimplePagination.java
gradle/libs.versions.toml
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/runtime/thirdparty/McVersion.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/runtime/thirdparty/ReflectionUtils.java
settings.gradle

Tested on:
- 1.21.3
- 1.21.1
- 1.20.2

Add 1.21.3 Support

---

inventory-framework-platform-paper/build.gradle

Set Paper platform target to JDK 21

---

build-logic/conventions/src/main/kotlin/LibraryConventionPlugin.kt
examples/minestom/src/main/kotlin/me/devnatan/inventoryframework/runtime/SampleServer.kt
examples/minestom/src/main/kotlin/me/devnatan/inventoryframework/runtime/command/GamemodeCommand.kt
examples/minestom/src/main/kotlin/me/devnatan/inventoryframework/runtime/command/IFExampleCommand.kt
examples/minestom/src/main/kotlin/me/devnatan/inventoryframework/runtime/view/Failing.kt
examples/minestom/src/main/kotlin/me/devnatan/inventoryframework/runtime/view/ScheduledView.kt
examples/minestom/src/main/kotlin/me/devnatan/inventoryframework/runtime/view/SimplePagination.kt
gradle/libs.versions.toml
inventory-framework-api/src/main/kotlin/me/devnatan/inventoryframework/ViewConfigBuilder.kt
inventory-framework-platform-minestom/build.gradle.kts
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/IFInventoryListener.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/MinestomViewContainer.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/MinestomViewer.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/View.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/ViewFrame.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/component/MinestomIemComponentBuilder.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/context/CloseContext.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/context/Context.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/context/OpenContext.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/context/RenderContext.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/context/SlotClickContext.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/context/SlotContext.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/context/SlotRenderContext.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/internal/MinestomElementFactory.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/internal/MinestomTaskJobImpl.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/pipeline/GlobalClickInterceptor.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/pipeline/ItemClickInterceptor.kt
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java

Fiuxes Build when exluding spotlessCheck

Fix Build System

---

inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/IFViewFrame.java

Closing inventory on open is not needed anymore.

fix: do not close inventory on open

---

examples/paper/src/main/java/me/devnatan/inventoryframework/runtime/SamplePlugin.java
examples/paper/src/main/java/me/devnatan/inventoryframework/runtime/listener/PigListener.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/Viewer.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/ViewFrame.java
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/ViewFrame.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/pipeline/GlobalClickInterceptor.kt
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/IFViewFrame.java

Can be reproduced by clicking on a PIG w/ mouse left & click at the same time.
Fixes https://github.com/DevNatan/inventory-framework/issues/744

fix: fast opens inconsistently setups viewers twice

---

examples/minestom/src/main/kotlin/me/devnatan/inventoryframework/runtime/view/SimplePagination.kt
gradle/libs.versions.toml
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/context/IFSlotClickContext.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/context/SlotClickContext.java
inventory-framework-platform-minestom/build.gradle.kts
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/IFInventoryListener.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/View.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/component/MinestomItemComponentBuilder.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/context/RenderContext.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/context/SlotClickContext.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/internal/MinestomElementFactory.kt

Now publishes Minestom module, and supports Minestom 1.21.5 branch. These changes won't be compatible with older versions and currently uses a branch specifier since the branch hasn't been merged to main branch. I've decided to make this a draft pull request until it's merged

feat: minestom 1.21.5 support
