src/main/java/me/saiintbrisson/minecraft/DelegatedViewProvider.java
src/main/java/me/saiintbrisson/minecraft/ViewFrame.java
src/main/java/me/saiintbrisson/minecraft/ViewProvider.java

Pessoalmente, eu costumo usar integrar toda a biblioteca do inventory-framework em um projeto único, mas isso provoca a execução de callbacks duplicados porque ao instanciar diversos ViewFrames as mesmas acabam duplicando o Listener do Bukkit.
O patch verifica se um registro anterior já está registrado nos serviços do Bukkit para impedir o registro do próximo listener que vai causar a duplicação.

Patch de resolução para prevenir callbacks duplicados

---

README.md

Material 'BLAZE_ROW' does not exist. The correct one would be 'BLAZE_ROD'.
I replaced all 'BLAZE_ROW' in the README examples with 'BLAZE_ROD'.

replaced 'BLAZE_ROW' to 'BLAZE_ROD'.

---

src/main/resources/plugin.yml

Plugins not using the `api-version` in plugin.yml introduced in 1.13 may lead to load the old legacy support.
See: https://www.spigotmc.org/wiki/plugin-yml/#optional-attributes

Add `api-version` to plugin.yml

---

bukkit-api/src/main/java/me/saiintbrisson/minecraft/BukkitClickViewSlotContext.java
bukkit-api/src/main/java/me/saiintbrisson/minecraft/BukkitPaginatedViewSlotContextImpl.java
bukkit-api/src/main/java/me/saiintbrisson/minecraft/BukkitViewComponentFactory.java
bukkit-api/src/main/java/me/saiintbrisson/minecraft/BukkitViewSlotContext.java
bukkit-api/src/main/java/me/saiintbrisson/minecraft/ViewListener.java
feature-move-io/src/main/java/me/saiintbrisson/minecraft/BukkitMoveOutInterceptor.java
feature-move-io/src/main/java/me/saiintbrisson/minecraft/BukkitViewSlotMoveClickContextImpl.java
shared/src/main/java/me/saiintbrisson/minecraft/AbstractView.java
shared/src/main/java/me/saiintbrisson/minecraft/AbstractViewSlotContext.java
shared/src/main/java/me/saiintbrisson/minecraft/BaseViewContext.java
shared/src/main/java/me/saiintbrisson/minecraft/ItemWrapper.java
shared/src/main/java/me/saiintbrisson/minecraft/PaginatedViewSlotContext.java
shared/src/main/java/me/saiintbrisson/minecraft/UnmodifiableViewContext.java
shared/src/main/java/me/saiintbrisson/minecraft/ViewComponentFactory.java
shared/src/main/java/me/saiintbrisson/minecraft/ViewSlotClickContext.java
shared/src/main/java/me/saiintbrisson/minecraft/ViewSlotContext.java
shared/src/main/java/me/saiintbrisson/minecraft/pipeline/interceptors/PaginationRenderInterceptor.java
shared/src/main/java/me/saiintbrisson/minecraft/pipeline/interceptors/RenderInterceptor.java
shared/src/main/java/me/saiintbrisson/minecraft/pipeline/interceptors/UpdateInterceptor.java
shared/src/test/java/me/saiintbrisson/minecraft/ContextDataInheritanceTest.java
shared/src/test/java/me/saiintbrisson/minecraft/MockComponentFactory.java
shared/src/test/java/me/saiintbrisson/minecraft/NoopViewComponentFactory.java

* Allows nullable values on pagination sources
* Fixes pagination context `getSlot()` returning index instead of current slot
* Fixes context `getCurrentItem`
* New `onSlotRender` prototype
* Now supports immediate `clear()` when context is on entity container
Closes #230, #223

Fix null slot context current item and pagination context slot

---

bukkit/src/main/java/me/devnatan/inventoryframework/internal/BukkitTaskJobImpl.java

Caused an "immediate update" and the initially defined title was not visible.

Wait for interval before start scheduled update job

---

framework/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java

To reproduce just use `Collections.emptyList()` in `paginationState` `sourceProvider` parameter
**Stack-trace**
```
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
at java.util.Collections$EmptyList.get(Unknown Source) ~[?:1.8.0_381]
at me.devnatan.inventoryframework.component.PaginationImpl.registerComponentsForLayeredPagination(PaginationImpl.java:398) ~[?:?]
```

Fix pagination error when a empty source is provided

---

api/src/main/java/me/devnatan/inventoryframework/component/Component.java
api/src/main/java/me/devnatan/inventoryframework/component/ComponentBuilder.java
api/src/main/java/me/devnatan/inventoryframework/component/ItemComponent.java
bukkit/src/main/java/me/devnatan/inventoryframework/component/BukkitItemComponentBuilder.java
framework/src/main/java/me/devnatan/inventoryframework/component/DefaultComponentBuilder.java
framework/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
platform/src/main/java/me/devnatan/inventoryframework/PaginationStateBuilder.java
platform/src/main/java/me/devnatan/inventoryframework/context/PlatformRenderContext.java
test/src/main/java/me/devnatan/inventoryframework/component/FakeComponent.java

Dynamically rendered items (`renderWith`/`onRender`) when used in `paginationState`, where placed in the wrong position.
**Reproducible code**
Works with or without layout.
```java
private final State<Pagination> paginationState = paginationState(
(context) -> <any non-empty source here>,
(item, value) -> item.renderWith(() -> new ItemStack(Material.PAPER))
);
@Override
public void onInit(ViewConfigBuilder config) {
config.cancelOnClick().layout(
"         ",
" OOOOOOO ",
"         "
);
}
```
| Before | After |
|:-:|:-:|
| ![image](https://github.com/DevNatan/inventory-framework/assets/24600258/51ce45b9-e5f6-4c4a-9fda-fa80ae818447) | ![image](https://github.com/DevNatan/inventory-framework/assets/24600258/89c94e52-e110-4839-b8dc-be7feffa54e3) |

Dynamically rendered items in pagination being positioned in the wrong place

---

api/src/main/java/me/devnatan/inventoryframework/component/ComponentBuilder.java
api/src/main/java/me/devnatan/inventoryframework/component/ItemComponent.java
bukkit/src/main/java/me/devnatan/inventoryframework/component/BukkitItemComponentBuilder.java
framework/src/main/java/me/devnatan/inventoryframework/component/DefaultComponentBuilder.java

Creates a shortcut to `onClick(IFContext::update)` by using `item.updateOnClick()`. This is especially to not break the beautified method chaining flow.
**Before**
```java
item.onClick(click -> {
doSomething();
click.update();
});
```
**After**
```java
item.updateOnClick().onClick(this::doSomething)
```

Create updateOnClick() overload

---

api/src/main/java/me/devnatan/inventoryframework/component/ItemComponent.java

Fixes usage of `updateOnClick` without `onClick` implemented in #418

Trigger update when `updateOnClick` is true and `clickHandler` is null

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/Pagination.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/state/AbstractStateValue.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/state/StateValue.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/state/ComputedValue.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/state/ImmutableValue.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/state/InitialDataStateValue.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/state/LazyValue.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/state/MutableValue.java

This is needed since some components are StateValue on its iplementation but cannot be on API because StateValue was a class previously

StateValue from API is now a interface

---

CHANGELOG.md
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/Component.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/ComponentBuilder.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/ItemComponent.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/context/IFContext.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/component/DefaultComponentBuilder.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/context/BaseViewContext.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/pipeline/FirstRenderInterceptor.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/component/BukkitItemComponentBuilder.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/context/SlotContext.java
inventory-framework-platform/src/test/java/me/devnatan/inventoryframework/component/TestItemComponentBuilder.java
inventory-framework-test/src/main/java/me/devnatan/inventoryframework/component/FakeComponent.java

Fixes #428
Before this PR the code below do not work very well.
What we expect is: `showIronState` is true? Show IRON_INGOT. Iron item visibility is based on `displayIf` but currently the GOLD_INGOT is always shown if it's declaration comes first or if it comes later, the iron item is shown and when `displayIf` becomes false - nothing is displayed at all the slot becames empty.
```java
MutableState<Boolean> showIronState = mutableState(false);
render.firstSlot(new ItemStack(Material.IRON_INGOT)).displayIf(() -> showIronState.get(context))
// ... an item to update `showIronState` state somehow ...
render.firstSlot(new ItemStack(Material.GOLD_INGOT));
```
We do not need a `watch(showIronState)` in IRON_INGOT item because `displayIf` reacts to any global update so `context.update()` works. …

Detect components overlap

---

inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/IFViewFrame.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java

Allows apply a default configuration for all views. This feature was available in version 2 and earlier.

`defaultConfig(...)` in ViewFrame to apply default configuration for views

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/PaginationElementConsumer.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PaginationStateBuilder.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java

Pagination element factory with context and index parameters

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/Component.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/ItemComponent.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/Pagination.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/PaginationValueConsumer.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/context/IFContext.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/context/IFRenderContext.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/context/IFUpdateContext.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/context/AbstractIFContext.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/pipeline/UpdateInterceptor.java
inventory-framework-core/src/test/java/me/devnatan/inventoryframework/pipeline/UpdateInterceptorTest.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/IFViewFrame.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PaginationStateBuilder.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/context/PlatformRenderContext.java
inventory-framework-test/src/main/java/me/devnatan/inventoryframework/component/FakeComponent.java

Fixes #453
paginationState methods that accepts Function-like parameter as source provider is now `computedPaginationState` to match `computedState`. Computed state is used to create endless pagination so only `Function` is accepted as source provider (`Supplier` was removed).
`asyncPaginationState` is now `computedAsyncPaginationState` to match `computedState` as well.
`lazyPaginationState` introduced to match `lazyState`.

Fix lazy pagination reloading

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/Component.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/ComponentComposition.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/ComponentContainer.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/context/IFContext.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/context/AbstractIFContext.java

Child components (components whose root is a Component and not a IFContext) were being ignored in the component overlap check. Also caused its root to be re-rendered X times, with   being the number of components that had `displayIf` in the view and that its position interfered with the position of the root of these components.
Ex.: a Clock item interfering in Pagination (see code below)
```java
State<Pagination> paginationState = lazyPaginationState(
(context) -> IntStream.range(0, 50).boxed().collect(Collectors.toList()), 
(context, builder, index, value) -> {
builder.withItem(new ItemStack(Material.DIAMOND));
}
);
@Override
public void onFirstRender(@NotNull RenderContext render) {
Pagination pagination = paginationState.get(render);
render.firstSlot(new ItemStack(Material.CLOCK)) …
```

Check overlaps in ComponentComposition child as well

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/Component.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/ComponentContainer.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/ItemComponent.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/PaginationElementFactory.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/context/IFContext.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/context/AbstractIFContext.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/pipeline/FirstRenderInterceptor.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/IFInventoryListener.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/context/SlotContext.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/pipeline/ItemClickInterceptor.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PaginationStateBuilder.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java
inventory-framework-test/src/main/java/me/devnatan/inventoryframework/component/FakeComponent.java

Now Pagination component uses context-centralized rendering mechanism that allows Pagination items use `displayIf` and `watch` as regular components. Also `getRoot()` of paginated items was fixed and now returns `Pagination` instead of IFContext.
#465 fixed issues related to regular components with `displayIf` not working with paginated items, this PR resolves: paginated items with `displayIf` not working with regular components with `displayIf`.
Now, this code works fine:
https://github.com/DevNatan/inventory-framework/assets/24600258/85ede378-5541-488f-bd37-7f229157252d
For now displayIf in paginated items do not affects reordering
```java
MutableState<Boolean> showOnlyClockState = mutableState(true);
State<Pagination> paginationState = paginationState(
IntStream.range(0, …
```

Fix usage of `displayIf` and `watch` in pagination items

---

inventory-framework-core/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java

Async lazy pagination was being marked as static pagination

Async lazy pagination crash - marked as static but it's never static

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/Pagination.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java

Force update allows developer to update an component ignoring any internal restriction.
onResume is called when `context.back()` is used

Call onResume on context back and allow forceUpdate

---

inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/IFViewFrame.java

Related to MC 1.8 using F6 keys to bypass inventory handlers, Bukkit do not dispatch InventoryCloseEvent if player uses F6 and then ESC

Force inventory of all viewers to be close before first open

---

inventory-framework-core/src/main/java/me/devnatan/inventoryframework/state/InitialDataStateValue.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/state/LazyValue.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java

back() causes a IllegalStateModificationException because LazyValue is immutable

Fix IllegalStateModificationException on back

---

inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/ViewFrame.java

Now bStats metrics can be disabled using `disableMetrics()`

Disable bStats metrics option

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/ViewConfig.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/ViewConfigBuilder.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/context/PlatformConfinedContext.java

Creates an option to always carry initial data from "A" to "B" on navigate. This is a bug because this was supposed to be the default behavior. An option was created to preserve the behavior of previously created views.
Can be enabled for a specific view using `transitiveInitialData(Boolean)`
```java
@Override
public void onInit(ViewConfigBuilder config) {
config.transitiveInitialData(true);
}
```
Enabled for all views on ViewFrame default config
```java
viewFrame.defaultConfig(config -> config.transitiveInitialData(true));
```
And be disabled for a specific view after enabling globally
```java
@Override
public void onInit(ViewConfigBuilder config) {
config.transitiveInitialData(false);
}
```
This options changes the behavior of `openToPlayer(Class)`.
Data provided in `openToPlayer(Class, …

Initial data transitivity option

---

inventory-framework-anvil-input/src/main/java/me/devnatan/inventoryframework/AnvilInputFeature.java

Anvil Input state is mutable but actually using `set(...)` doesn't change ingredient item display name

Update Anvil Input ingredient item display name on state value set

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/ComponentBuilder.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/ItemComponent.java

Ensures that component use unified update & re-render mechanism to determine it's own visibility instead of removing it manually from current container (which is wrong).
Currently `hide()` calls `setVisible(false)` then `clear()` that removes physical component from the container.
Now `hide()` calls `setVisible(false)` then `update()` that relies on unified context-hold update & re-render mechanism to determine if that component must be visible or not also, this mechanism determines if other components like overlapping ones should be shown when this component gets shown/hidden.
The major problem here is that `clear() removes physical component from the container, virtual component stills so any interaction on the empty slot will call that (currently hidden) component, interactions …

Use regular update mechanism to determine component visibility on change

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/Viewer.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/BukkitViewer.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/View.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/ViewFrame.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/pipeline/ItemCloseOnClickInterceptor.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/IFViewFrame.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/pipeline/ContextInvalidationOnCloseInterceptor.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/pipeline/PlatformOpenInterceptor.java

`onViewerAdded`/`onViewerRemoved` to know when a player joins/leaves a context
`openActiveContext` to allow a player to "join" a shared context
`open(...)` now returns generated context id
Closes #510

Shared contexts enhancements

---

inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/BukkitViewer.java

Allows the use of state for a single player instead of all players in a context. Designed to use with [shared contexts](https://github.com/DevNatan/inventory-framework/wiki/Shared-Contexts).
**Not tested - Extremelly experimental** 
```java
myState.get(ctx.getViewer())...
```

Per-viewer state management

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/internal/LayoutSlot.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/pipeline/AvailableSlotInterceptor.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/component/PaginationBuilder.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/context/PlatformRenderContext.java

Now is possible to use `render.layoutSlot('O')` as well. This restriction is not needed anymore.

Remove reserved layout character restriction

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/context/IFRenderContext.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/state/DefaultStateValueHost.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/state/StateRegistryImpl.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/context/DefaultSlotComponentRenderer.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/context/PlatformRenderContext.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/context/SlotComponentRenderer.java

Resolve layout before first render

---

inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/internal/BukkitElementFactory.java

Allows use o Layouts in non-chest inventory types like DISPENSER

fix: ignore extendable container checks on contexts w/ layouts

---

inventory-framework-anvil-input/src/main/java/me/devnatan/inventoryframework/AnvilInputFeature.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/state/StateValueHost.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/state/BaseMutableState.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/state/DefaultStateValueHost.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/state/MutableGenericStateImpl.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/context/CloseContext.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/context/SlotContext.java
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/context/CloseContext.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/context/SlotContext.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/pipeline/GlobalClickInterceptor.kt

Allows state to be updated while another state is being initialized e.g.: a lazy/computed state on its first data load. Also allows state values to be set on shared context before "sending" it to the player.

feat: allow earlier state update

---

.github/workflows/publish.yml
build-logic/conventions/build.gradle.kts
build-logic/conventions/src/main/kotlin/LibraryConventionPlugin.kt
build-logic/conventions/src/main/kotlin/Publish.kt
build.gradle.kts
gradle.properties
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
inventory-framework-anvil-input/build.gradle.kts
inventory-framework-api/build.gradle.kts
inventory-framework-platform-bukkit/build.gradle.kts
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/runtime/InventoryFramework.java
inventory-framework-platform-minestom/build.gradle.kts
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/pipeline/GlobalClickInterceptor.kt

OSSRH service will reach the end of life and dashboard is insanely buggy. This PR change release and snapshot publication urls to the new Maven Central publisher urls

chore: use new Maven Central publication mechanism

---

.github/workflows/publish.yml
build-logic/conventions/src/main/kotlin/Extension.kt
build-logic/conventions/src/main/kotlin/GenerateVersionFileTask.kt
build-logic/conventions/src/main/kotlin/LibraryConventionPlugin.kt
build-logic/conventions/src/main/kotlin/Publish.kt
build.gradle.kts
inventory-framework-platform-bukkit/build.gradle.kts
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/ViewFrame.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/runtime/InventoryFramework.java
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/ViewFrame.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/pipeline/GlobalClickInterceptor.kt

* Now plugin version on current build is based on the next release tag
* Due to this ^, version file is now auto-generated
* Fixed "inventory framework is shaded" message when using relocate
To create a .jar with a custom version is needed to pass use `version` property
```
./gradlew -Pversion=1.99.0 shadowJar
```

fix: relocation and versioning issues

---

inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/IFInventoryListener.java

Since we removed early close to prevent flickering, now InventoryCloseEvent is being called after InventoryOpenEvent is called to the next inventory, this behavior causes a bug when transitioning from a non-InventoryFramework to a InventoryFramework view.

fix: broken view while transitioning from non-IF inventories

---

inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/context/RenderContext.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/internal/MinestomElementFactory.kt

This PR fixes an issue that occurs when opening a view on Minestom. (#732)
<details>
<summary>Issue</summary>
```
java.lang.NullPointerException: Parameter specified as non-null is null: method me.devnatan.inventoryframework.internal.MinestomElementFactory.createRenderContext, parameter container
at me.devnatan.inventoryframework.internal.MinestomElementFactory.createRenderContext(MinestomElementFactory.kt)
at me.devnatan.inventoryframework.pipeline.PlatformOpenInterceptor.createRenderContext(PlatformOpenInterceptor.java:74)
at me.devnatan.inventoryframework.pipeline.PlatformOpenInterceptor.finishOpen(PlatformOpenInterceptor.java:53)
at me.devnatan.inventoryframework.pipeline.PlatformOpenInterceptor.intercept(PlatformOpenInterceptor.java:29)
at …
```

Fix issue IF not working on Minestom

---

gradle/libs.versions.toml

In MC 1.21 org.bukkit.inventory.InventoryView became a `interface` (previously a `class`) so Dynamic Title Update that interacts with it directly throws a IncompatibleClassChangeError on pre MC 1.21 servers.
The workaround for that is using MC 1.20.6 dependency as we do not use any MC 1.21 specific API yet.
How to reproduce: try to use `context.updateTitle` using latest Inventory Framework version in a server that is not MC 1.21.
Stack trace:
```
[18:45:19 WARN]: java.lang.IncompatibleClassChangeError: Found class org.bukkit.inventory.InventoryView, but interface was expected
[18:45:19 WARN]:        at me.devnatan.inventoryframework.runtime.thirdparty.InventoryUpdate.updateInventory(InventoryUpdate.java:146)
[18:45:19 WARN]:        at …
```

fix: IncompatibleClassChangeError on Dynamic Title Update pre MC 1.20.6

---

examples/paper/build.gradle.kts
inventory-framework-anvil-input/src/main/java/me/devnatan/inventoryframework/AnvilInputNMS.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/runtime/thirdparty/ReflectionUtils.java

PlayerConnection field name is `g` in 1.21.6/1.21.7.
https://mappings.dev/1.21.6/net/minecraft/server/level/ServerPlayer.html
Closes #763

feat: Anvil Input MC 1.21.6/1.21.7 support

---

THIRDPARTY.md
examples/paper/build.gradle.kts
examples/paper/src/main/java/me/devnatan/inventoryframework/runtime/SamplePlugin.java
examples/paper/src/main/java/me/devnatan/inventoryframework/runtime/commands/IFExampleCommandExecutor.java
gradle/libs.versions.toml
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/PaginationStateBuilder.java
inventory-framework-api/src/main/java/me/devnatan/inventoryframework/context/IFSlotClickContext.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/state/StateAccessImpl.java
inventory-framework-platform-bukkit/build.gradle.kts
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/ViewFrame.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/internal/BukkitElementFactory.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/internal/BukkitTaskJobImpl.java
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/IFInventoryListener.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/context/SlotClickContext.kt
inventory-framework-platform-minestom/src/main/kotlin/me/devnatan/inventoryframework/internal/MinestomElementFactory.kt
inventory-framework-platform-paper/build.gradle.kts
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/PlatformView.java
settings.gradle.kts

Closes https://github.com/DevNatan/inventory-framework/issues/339

feat: folia support

---

inventory-framework-api/src/main/java/me/devnatan/inventoryframework/component/Pagination.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/component/PaginationImpl.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/context/AbstractIFContext.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/pipeline/AvailableSlotInterceptor.java
inventory-framework-core/src/main/java/me/devnatan/inventoryframework/pipeline/LayoutRenderInterceptor.java
inventory-framework-platform/src/main/java/me/devnatan/inventoryframework/context/PlatformRenderContext.java

Fixes layout and pagination items overlap. The use case is: when you need to render the "empty slots" of pagination with a placeholder item. Currently this is not possible but it is not the indeed behavior.
Create a pagination using some character as layout target then use `layoutSlot(<the same character>)`.
✅ **Expected behavior:**
1. Pagination renders first
2. `layoutSlot([...])` renders in the slots that pagination couldn't reach (due to not enough source)
3. Changing pages only affects Pagination
❌ **Current behavior:**
1. `layoutSlot([...])` renders in all slots
2. Pagination renders "below" (IF supports Overlapping Items so there's a "above"/"below" concept) `layoutSlot`
3. Changing pages only affects Pagination
**Sample code:**
```java
State<Pagination> paginationState = …
```

fix: layout and pagination items overlap

---

inventory-framework-anvil-input/src/main/java/me/devnatan/inventoryframework/AnvilInputNMS.java
inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/ViewFrame.java

This fixes the issue outlined in #773 and the relocation detection not working correctly

Minor Fixes
